# Generated by Django 5.2.3 on 2025-07-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ConversionHistory',
        ),
    ]
