# Generated by Django 5.2.3 on 2025-07-15 10:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_type', models.CharField(choices=[('pdf_to_word', 'PDF to Word'), ('word_to_pdf', 'Word to PDF'), ('pdf_to_excel', 'PDF to Excel'), ('excel_to_pdf', 'Excel to PDF'), ('pdf_to_image', 'PDF to Image'), ('image_to_pdf', 'Image to PDF')], max_length=20)),
                ('original_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='converted/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('converted_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
