# Generated by Django 5.2.3 on 2025-07-16 05:18

import apps.conversions.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionrequest',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conversionrequest',
            name='converted_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.conversions.models.user_converted_path),
        ),
        migrations.AlterField(
            model_name='conversionrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversionrequest',
            name='original_file',
            field=models.FileField(upload_to=apps.conversions.models.user_upload_path),
        ),
        migrations.AlterField(
            model_name='conversionrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
