# Generated by Django 5.2.3 on 2025-07-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0002_conversionrequest_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
