# Generated by Django 5.2.3 on 2025-07-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0004_convertedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConvertedFile',
        ),
    ]
