# Generated by Django 4.2 on 2025-12-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0005_delete_convertedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversionrequest',
            options={},
        ),
        migrations.AlterField(
            model_name='conversionrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
